# Generated by Django 3.1.7 on 2021-03-16 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnoclase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asistio', models.IntegerField(default=-1, verbose_name='Asistencia')),
                ('status', models.IntegerField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'alumnoclase',
                'verbose_name_plural': 'alumnoclases',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('status', models.IntegerField(default=1, verbose_name='Estado')),
                ('profesor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('dni_teacher', models.CharField(max_length=18, verbose_name='DNI del Profesor')),
                ('date_class', models.DateField(verbose_name='Fecha de Clase')),
                ('status', models.IntegerField(default=1, verbose_name='Estado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
            ],
            options={
                'verbose_name': 'clase',
                'verbose_name_plural': 'clases',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion', models.CharField(choices=[('P1', 'PRACTICA 1.'), ('P2', 'PRACTICA 2.'), ('P3', 'PRACTICA 3.'), ('P4', 'PRACTICA 4.'), ('EP', 'PARCIAL.'), ('EF', 'FINAL.'), ('ES', 'SUSTITUTORIO.'), ('PC', 'PARTICIPACION EN CLASE.')], max_length=3, verbose_name='Tipo de Evaluacion')),
                ('note', models.IntegerField(default=0, verbose_name='Nota')),
                ('status', models.IntegerField(default=1, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora de Creacion')),
                ('alumnoclase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumnoclase')),
            ],
            options={
                'verbose_name': 'calificacion',
                'verbose_name_plural': 'calificaciones',
                'ordering': ['evaluacion', 'note'],
            },
        ),
        migrations.AddField(
            model_name='alumnoclase',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clase'),
        ),
        migrations.AddField(
            model_name='alumnoclase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
