# Generated by Django 3.1.7 on 2021-04-07 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('001', 'Activado'), ('002', 'Desactivado')], default='001', max_length=3, verbose_name='Estado')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('001', 'Activado'), ('002', 'Desactivado')], default='001', max_length=3, verbose_name='Estado')),
                ('url', models.CharField(max_length=200, verbose_name='Url')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='seguridad.menu')),
            ],
            options={
                'verbose_name': 'menuitem',
                'verbose_name_plural': 'menuitems',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Perfil')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('estado', models.CharField(choices=[('001', 'Activado'), ('002', 'Desactivado')], default='001', max_length=3, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellidos', models.CharField(default='', max_length=100)),
                ('correo', models.EmailField(max_length=50)),
                ('estado', models.CharField(choices=[('001', 'Activado'), ('002', 'Desactivado')], default='001', max_length=3, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='seguridad.perfil')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('view', models.CharField(default='0', max_length=1, verbose_name='view')),
                ('create', models.CharField(default='0', max_length=1, verbose_name='create')),
                ('update', models.CharField(default='0', max_length=1, verbose_name='update')),
                ('delete', models.CharField(default='0', max_length=1, verbose_name='delete')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios', to='seguridad.menuitem')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios', to='seguridad.perfil')),
            ],
            options={
                'verbose_name': 'privilegio',
                'verbose_name_plural': 'privilegios',
                'ordering': ['perfil', 'menuitem'],
            },
        ),
    ]
