# Generated by Django 3.1.7 on 2021-04-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(help_text='Ingrese solo alfanumericos', max_length=200, verbose_name='Nombre de Perfil'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
