# Generated by Django 3.1.7 on 2021-04-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_auto_20210415_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
